version: "3"

services:

  python:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: test_django
    container_name: test_django_container
    command: bash -c " if [ ! -d "django_api_one" ]; then django-admin startproject django_api_one; fi && cd django_api_one && if [ ! -d "profiles_api" ]; then python3 manage.py startapp profiles_api; fi && python3 manage.py runserver 0.0.0.0:8000 "
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
    restart: always

volumes:
  db_volume:

    # redis:
    #   image: redis:alpine
    #   container_name: redis
    #   depends_on:
    #     - db

    # celery:
    #   restart: always
    #   build:
    #     context: .
    #   command: celery -A blog_project worker -l INFO
    #   volumes:
    #     - .:/app
    #   container_name: celery
    #   depends_on:
    #     - db
    #     - redis
    #     - python
